local sfx = {}

sfx.bgmusic = audio.loadSound("audio/bgmusic.wav")	
sfx.click = audio.loadSound("audio/click.wav")						--32														
sfx.choices = audio.loadSound("audio/choices.wav")					--31									
sfx.congratulations = audio.loadSound("audio/congratulations.wav")	--30
sfx.correct_answer = audio.loadSound("audio/correct_answer.wav")  	--29
sfx.end_levelfail = audio.loadSound("audio/end_levelfail.wav")		--28
sfx.drumroll = audio.loadSound("audio/drumroll.wav")				--27
sfx.fail = audio.loadSound("audio/fail button.wav")					--26
sfx.tada = audio.loadSound("audio/tadaa.wav")						--25
sfx.try_again = audio.loadSound("audio/try_again.wav")				--24	

sfx.level1s1 = audio.loadSound("audio/english/girl/level1/level1-1.wav")	
sfx.level1s2 = audio.loadSound("audio/english/girl/level1/level1-2.wav")	
sfx.level1s3 = audio.loadSound("audio/english/girl/level1/level1-3.wav")	
sfx.level1s4 = audio.loadSound("audio/english/girl/level1/level1-4.wav")	
sfx.level1s5 = audio.loadSound("audio/english/girl/level1/level1-5.wav")	
sfx.level1s6 = audio.loadSound("audio/english/girl/level1/level1-6.wav")	
sfx.level1s7 = audio.loadSound("audio/english/girl/level1/level1-7.wav")	
sfx.time1s1 = audio.getDuration(sfx.level1s1)
sfx.time1s2 = audio.getDuration(sfx.level1s2)
sfx.time1s3 = audio.getDuration(sfx.level1s3)
sfx.time1s4 = audio.getDuration(sfx.level1s4)
sfx.time1s5 = audio.getDuration(sfx.level1s5)
sfx.time1s6 = audio.getDuration(sfx.level1s6)
sfx.time1s7 = audio.getDuration(sfx.level1s7)

sfx.level2s1 = audio.loadSound("audio/english/girl/level2/level2-1.wav")	
sfx.level2s2 = audio.loadSound("audio/english/girl/level2/level2-2.wav")	
sfx.level2s3 = audio.loadSound("audio/english/girl/level2/level2-3.wav")	
sfx.level2s4 = audio.loadSound("audio/english/girl/level2/level2-4.wav")	
sfx.level2s5 = audio.loadSound("audio/english/girl/level2/level2-5.wav")	
sfx.time2s1 = audio.getDuration(sfx.level2s1)
sfx.time2s2 = audio.getDuration(sfx.level2s2)
sfx.time2s3 = audio.getDuration(sfx.level2s3)
sfx.time2s4 = audio.getDuration(sfx.level2s4)
sfx.time2s5 = audio.getDuration(sfx.level2s5)

sfx.level3s1 = audio.loadSound("audio/english/girl/level3/level3-1.wav")	
sfx.level3s2 = audio.loadSound("audio/english/girl/level3/level3-2.wav")	
sfx.level3s3 = audio.loadSound("audio/english/girl/level3/level3-3.wav")	
sfx.level3s4 = audio.loadSound("audio/english/girl/level3/level3-4.wav")	
sfx.level3s5 = audio.loadSound("audio/english/girl/level3/level3-5.wav")	
sfx.time3s1 = audio.getDuration(sfx.level3s1)
sfx.time3s2 = audio.getDuration(sfx.level3s2)
sfx.time3s3 = audio.getDuration(sfx.level3s3)
sfx.time3s4 = audio.getDuration(sfx.level3s4)
sfx.time3s5 = audio.getDuration(sfx.level3s5)

sfx.level4s1 = audio.loadSound("audio/english/boy/level4/level4-1.wav")		
sfx.level4s2 = audio.loadSound("audio/english/boy/level4/level4-2.wav")		
sfx.level4s3 = audio.loadSound("audio/english/boy/level4/level4-3.wav")		
sfx.level4s4 = audio.loadSound("audio/english/boy/level4/level4-4.wav")		
sfx.level4s5 = audio.loadSound("audio/english/boy/level4/level4-5.wav")		
sfx.time4s1 = audio.getDuration(sfx.level4s1)
sfx.time4s2 = audio.getDuration(sfx.level4s2)
sfx.time4s3 = audio.getDuration(sfx.level4s3)
sfx.time4s4 = audio.getDuration(sfx.level4s4)
sfx.time4s5 = audio.getDuration(sfx.level4s5)

sfx.level4s1G = audio.loadSound("audio/english/girl/level4/level4-1.wav")	
sfx.level4s2G = audio.loadSound("audio/english/girl/level4/level4-2.wav")	
sfx.level4s3G = audio.loadSound("audio/english/girl/level4/level4-3.wav")	
sfx.level4s4G = audio.loadSound("audio/english/girl/level4/level4-4.wav")	
sfx.level4s5G = audio.loadSound("audio/english/girl/level4/level4-5.wav")	
sfx.time4s1G = audio.getDuration(sfx.level4s1G)
sfx.time4s2G = audio.getDuration(sfx.level4s2G)
sfx.time4s3G = audio.getDuration(sfx.level4s3G)
sfx.time4s4G = audio.getDuration(sfx.level4s4G)
sfx.time4s5G = audio.getDuration(sfx.level4s5G)

sfx.level5s1 = audio.loadSound("audio/english/girl/level5/level5-1.wav")	
sfx.level5s2 = audio.loadSound("audio/english/girl/level5/level5-2.wav")	
sfx.level5s3 = audio.loadSound("audio/english/girl/level5/level5-3.wav")	
sfx.level5s4 = audio.loadSound("audio/english/girl/level5/level5-4.wav")	
sfx.time5s1 = audio.getDuration(sfx.level5s1)
sfx.time5s2 = audio.getDuration(sfx.level5s2)
sfx.time5s3 = audio.getDuration(sfx.level5s3)
sfx.time5s4 = audio.getDuration(sfx.level5s4)

-- tagalog
sfx.level1s1t = audio.loadSound("audio/tagalog/girl/level1/level1-1.wav")	
sfx.level1s2t = audio.loadSound("audio/tagalog/girl/level1/level1-2.wav")	
sfx.level1s3t = audio.loadSound("audio/tagalog/girl/level1/level1-3.wav")	
sfx.level1s4t = audio.loadSound("audio/tagalog/girl/level1/level1-4.wav")	
sfx.level1s5t = audio.loadSound("audio/tagalog/girl/level1/level1-5.wav")	
sfx.level1s6t = audio.loadSound("audio/tagalog/girl/level1/level1-6.wav")	
sfx.level1s7t = audio.loadSound("audio/tagalog/girl/level1/level1-7.wav")	
sfx.time1s1t = audio.getDuration(sfx.level1s1t)
sfx.time1s2t = audio.getDuration(sfx.level1s2t)
sfx.time1s3t = audio.getDuration(sfx.level1s3t)
sfx.time1s4t = audio.getDuration(sfx.level1s4t)
sfx.time1s5t = audio.getDuration(sfx.level1s5t)
sfx.time1s6t = audio.getDuration(sfx.level1s6t)
sfx.time1s7t = audio.getDuration(sfx.level1s7t)

sfx.level2s1t = audio.loadSound("audio/tagalog/girl/level2/level2-1.wav")	
sfx.level2s2t = audio.loadSound("audio/tagalog/girl/level2/level2-2.wav")	
sfx.level2s3t = audio.loadSound("audio/tagalog/girl/level2/level2-3.wav")	
sfx.level2s4t = audio.loadSound("audio/tagalog/girl/level2/level2-4.wav")	
sfx.level2s5t = audio.loadSound("audio/tagalog/girl/level2/level2-5.wav")	
sfx.time2s1t = audio.getDuration(sfx.level2s1t)
sfx.time2s2t = audio.getDuration(sfx.level2s2t)
sfx.time2s3t = audio.getDuration(sfx.level2s3t)
sfx.time2s4t = audio.getDuration(sfx.level2s4t)
sfx.time2s5t = audio.getDuration(sfx.level2s5t)

sfx.level3s1t = audio.loadSound("audio/tagalog/girl/level3/level3-1.wav")	
sfx.level3s2t = audio.loadSound("audio/tagalog/girl/level3/level3-2.wav")	
sfx.level3s3t = audio.loadSound("audio/tagalog/girl/level3/level3-3.wav")	
sfx.level3s4t = audio.loadSound("audio/tagalog/girl/level3/level3-4.wav")	
sfx.level3s5t = audio.loadSound("audio/tagalog/girl/level3/level3-5.wav")	
sfx.time3s1t = audio.getDuration(sfx.level3s1t)
sfx.time3s2t = audio.getDuration(sfx.level3s2t)
sfx.time3s3t = audio.getDuration(sfx.level3s3t)
sfx.time3s4t = audio.getDuration(sfx.level3s4t)
sfx.time3s5t = audio.getDuration(sfx.level3s5t)

sfx.level4s1t = audio.loadSound("audio/tagalog/boy/level4/level4-1.wav")	
sfx.level4s2t = audio.loadSound("audio/tagalog/boy/level4/level4-2.wav")	
sfx.level4s3t = audio.loadSound("audio/tagalog/boy/level4/level4-3.wav")	
sfx.level4s4t = audio.loadSound("audio/tagalog/boy/level4/level4-4.wav")	
sfx.level4s5t = audio.loadSound("audio/tagalog/boy/level4/level4-5.wav")	
sfx.time4s1t = audio.getDuration(sfx.level4s1t)
sfx.time4s2t = audio.getDuration(sfx.level4s2t)
sfx.time4s3t = audio.getDuration(sfx.level4s3t)
sfx.time4s4t = audio.getDuration(sfx.level4s4t)
sfx.time4s5t = audio.getDuration(sfx.level4s5t)

sfx.level4s1Gt = audio.loadSound("audio/tagalog/girl/level4/level4-1.wav")	
sfx.level4s2Gt = audio.loadSound("audio/tagalog/girl/level4/level4-2.wav")	
sfx.level4s3Gt = audio.loadSound("audio/tagalog/girl/level4/level4-3.wav")	
sfx.level4s4Gt = audio.loadSound("audio/tagalog/girl/level4/level4-4.wav")	
sfx.level4s5Gt = audio.loadSound("audio/tagalog/girl/level4/level4-5.wav")	
sfx.time4s1Gt = audio.getDuration(sfx.level4s1Gt)
sfx.time4s2Gt = audio.getDuration(sfx.level4s2Gt)
sfx.time4s3Gt = audio.getDuration(sfx.level4s3Gt)
sfx.time4s4Gt = audio.getDuration(sfx.level4s4Gt)
sfx.time4s5Gt = audio.getDuration(sfx.level4s5Gt)

sfx.level5s1t = audio.loadSound("audio/tagalog/girl/level5/level5-1.wav")	
sfx.level5s2t = audio.loadSound("audio/tagalog/girl/level5/level5-2.wav")	
sfx.level5s3t = audio.loadSound("audio/tagalog/girl/level5/level5-3.wav")	
sfx.level5s4t = audio.loadSound("audio/tagalog/girl/level5/level5-4.wav")	
sfx.time5s1t = audio.getDuration(sfx.level5s1t)
sfx.time5s2t = audio.getDuration(sfx.level5s2t)
sfx.time5s3t = audio.getDuration(sfx.level5s3t)
sfx.time5s4t = audio.getDuration(sfx.level5s4t)

--bicol
sfx.level1s1g = audio.loadSound("audio/bicol/girl/level1/level1-1.wav")	
sfx.level1s2g = audio.loadSound("audio/bicol/girl/level1/level1-2.wav")	
sfx.level1s3g = audio.loadSound("audio/bicol/girl/level1/level1-3.wav")	
sfx.level1s4g = audio.loadSound("audio/bicol/girl/level1/level1-4.wav")	
sfx.level1s5g = audio.loadSound("audio/bicol/girl/level1/level1-5.wav")	
sfx.level1s6g = audio.loadSound("audio/bicol/girl/level1/level1-6.wav")	
sfx.level1s7g = audio.loadSound("audio/bicol/girl/level1/level1-7.wav")	
sfx.time1s1g = audio.getDuration(sfx.level1s1g)
sfx.time1s2g = audio.getDuration(sfx.level1s2g)
sfx.time1s3g = audio.getDuration(sfx.level1s3g)
sfx.time1s4g = audio.getDuration(sfx.level1s4g)
sfx.time1s5g = audio.getDuration(sfx.level1s5g)
sfx.time1s6g = audio.getDuration(sfx.level1s6g)
sfx.time1s7g = audio.getDuration(sfx.level1s7g)

sfx.level2s1g = audio.loadSound("audio/bicol/girl/level2/level2-1.wav")	
sfx.level2s2g = audio.loadSound("audio/bicol/girl/level2/level2-2.wav")	
sfx.level2s3g = audio.loadSound("audio/bicol/girl/level2/level2-3.wav")	
sfx.level2s4g = audio.loadSound("audio/bicol/girl/level2/level2-4.wav")	
sfx.level2s5g = audio.loadSound("audio/bicol/girl/level2/level2-5.wav")	
sfx.time2s1g = audio.getDuration(sfx.level2s1g)
sfx.time2s2g = audio.getDuration(sfx.level2s2g)
sfx.time2s3g = audio.getDuration(sfx.level2s3g)
sfx.time2s4g = audio.getDuration(sfx.level2s4g)
sfx.time2s5g = audio.getDuration(sfx.level2s5g)

sfx.level3s1g = audio.loadSound("audio/bicol/girl/level3/level3-1.wav")	
sfx.level3s2g = audio.loadSound("audio/bicol/girl/level3/level3-2.wav")	
sfx.level3s3g = audio.loadSound("audio/bicol/girl/level3/level3-3.wav")	
sfx.level3s4g = audio.loadSound("audio/bicol/girl/level3/level3-4.wav")	
sfx.level3s5g = audio.loadSound("audio/bicol/girl/level3/level3-5.wav")	
sfx.time3s1g = audio.getDuration(sfx.level3s1g)
sfx.time3s2g = audio.getDuration(sfx.level3s2g)
sfx.time3s3g = audio.getDuration(sfx.level3s3g)
sfx.time3s4g = audio.getDuration(sfx.level3s4g)
sfx.time3s5g = audio.getDuration(sfx.level3s5g)

sfx.level4s1g = audio.loadSound("audio/bicol/boy/level4/level4-1.wav")		
sfx.level4s2g = audio.loadSound("audio/bicol/boy/level4/level4-2.wav")		
sfx.level4s3g = audio.loadSound("audio/bicol/boy/level4/level4-3.wav")		
sfx.level4s4g = audio.loadSound("audio/bicol/boy/level4/level4-4.wav")		
sfx.level4s5g = audio.loadSound("audio/bicol/boy/level4/level4-5.wav")		
sfx.time4s1g = audio.getDuration(sfx.level4s1g)
sfx.time4s2g = audio.getDuration(sfx.level4s2g)
sfx.time4s3g = audio.getDuration(sfx.level4s3g)
sfx.time4s4g = audio.getDuration(sfx.level4s4g)
sfx.time4s5g = audio.getDuration(sfx.level4s5g)

sfx.level4s1Gg = audio.loadSound("audio/bicol/girl/level4/level4-1.wav")	
sfx.level4s2Gg = audio.loadSound("audio/bicol/girl/level4/level4-2.wav")	
sfx.level4s3Gg = audio.loadSound("audio/bicol/girl/level4/level4-3.wav")	
sfx.level4s4Gg = audio.loadSound("audio/bicol/girl/level4/level4-4.wav")	
sfx.level4s5Gg = audio.loadSound("audio/bicol/girl/level4/level4-5.wav")	
sfx.time4s1Gg = audio.getDuration(sfx.level4s1Gg)
sfx.time4s2Gg = audio.getDuration(sfx.level4s2Gg)
sfx.time4s3Gg = audio.getDuration(sfx.level4s3Gg)
sfx.time4s4Gg = audio.getDuration(sfx.level4s4Gg)
sfx.time4s5Gg = audio.getDuration(sfx.level4s5Gg)

sfx.level5s1g = audio.loadSound("audio/bicol/girl/level5/level5-1.wav")	
sfx.level5s2g = audio.loadSound("audio/bicol/girl/level5/level5-2.wav")	
sfx.level5s3g = audio.loadSound("audio/bicol/girl/level5/level5-3.wav")	
sfx.level5s4g = audio.loadSound("audio/bicol/girl/level5/level5-4.wav")	
sfx.time5s1g = audio.getDuration(sfx.level5s1g)
sfx.time5s2g = audio.getDuration(sfx.level5s2g)
sfx.time5s3g = audio.getDuration(sfx.level5s3g)
sfx.time5s4g = audio.getDuration(sfx.level5s4g)

return sfx

